
import React from 'react';
import { Task, Habit, Priority, Category, Challenge } from './types';

export const INITIAL_TASKS: Task[] = [];

export const DEFAULT_CHALLENGES: Challenge[] = [
  {
    id: 'ch-sniper',
    title: 'Sniper Focus',
    description: 'Complete 100% of your daily tasks for 3 consecutive days.',
    targetDays: 3,
    currentStreak: 0,
    isActive: false,
    isCompleted: false
  },
  {
    id: 'ch-guardian',
    title: 'Prayer Guardian',
    description: 'Complete all 5 prayers on time for 7 consecutive days.',
    targetDays: 7,
    currentStreak: 0,
    isActive: false,
    isCompleted: false
  },
  {
    id: 'ch-no-delay',
    title: 'Zero Delay',
    description: 'Finish all tasks without a single postponement for 5 days.',
    targetDays: 5,
    currentStreak: 0,
    isActive: false,
    isCompleted: false
  }
];

export const GOAL_TASK_MAPPING: Record<string, Partial<Task>> = {
  /* Added time to Task interface enables these assignments */
  'Study': { title: 'Focused Study Session', category: Category.STUDY, priority: Priority.HIGH, time: '10:00 AM' },
  'Habits': { title: 'Track Morning Habits', category: Category.HABIT, priority: Priority.NORMAL, time: '08:30 AM' },
  'Prayers': { title: 'Morning Prayer & Reflection', category: Category.PRAYER, priority: Priority.HIGH, time: '05:00 AM' },
  'Health': { title: 'Quick Physical Stretch', category: Category.HABIT, priority: Priority.NORMAL, time: '07:30 AM' },
  'Finance': { title: 'Daily Budget Review', category: Category.STUDY, priority: Priority.NORMAL, time: '06:00 PM' },
  'Work': { title: 'Email & Schedule Audit', category: Category.STUDY, priority: Priority.NORMAL, time: '09:00 AM' },
};

export const INITIAL_HABITS: Habit[] = [
  /* Corrected history typing and property alignment */
  { id: 'h1', name: 'Drink 2L Water', streakCount: 12, isCompletedToday: false, lastCompletedDate: '', createdAt: new Date().toISOString(), description: 'Maintaining daily hydration for peak performance.', history: {} },
  { id: 'h2', name: 'Meditation', streakCount: 5, isCompletedToday: true, lastCompletedDate: new Date().toLocaleDateString(), createdAt: new Date().toISOString(), description: 'Morning mindfulness to start the day with clarity.', history: { [new Date().toISOString().split('T')[0]]: true } },
  { id: 'h3', name: 'Reading', streakCount: 8, isCompletedToday: false, lastCompletedDate: '', createdAt: new Date().toISOString(), description: 'Daily intellectual growth.', history: {} },
];

export const GOAL_OPTIONS = ['Study', 'Habits', 'Prayers', 'Health', 'Finance', 'Work'];

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    tasks: 'Tasks',
    habits: 'Habits',
    inbox: 'Inbox',
    stats: 'Stats',
    tips: 'Tips',
    settings: 'Settings',
    profile: 'Profile',
    brainDump: 'Brain Dump',
    welcome: 'Welcome',
    welcome_back: 'Welcome Back',
    goodMorning: 'Good Morning',
    justBreathe: 'Just breathe.',
    topPriority: 'Focus for today?',
    dailyFocus: 'Daily Focus',
    whatIsFocus: 'What is your focus today?',
    organizedDay: 'Let\'s get your day organized.',
    welcomeUser: 'Welcome, {name}',
    newTask: 'New Task',
    editTask: 'Edit Task',
    taskTitle: 'Task Title',
    label: 'Label',
    minutes: 'Minutes',
    priority: 'Priority',
    category: 'Category',
    add: 'Add Task',
    update: 'Update Task',
    cancel: 'Cancel',
    save: 'Save Changes',
    startTask: 'Start Task',
    done: 'Done',
    todo: 'To Do',
    timeline: 'Today\'s Timeline',
    urgent: 'Urgent',
    important: 'Important',
    normal: 'Normal',
    startTimer: 'Start Timer',
    running: 'Running...',
    recordingFocus: 'Recording Focus',
    remove: 'Remove',
    archiveDone: 'Archive Completed',
    listClear: 'List is clear',
    focusOutput: 'Focus on the output, not the hours.',
    organizeBtn: 'Organize My Day',
    organizing: 'AI Thinking...',
    victoryTitle: 'You were on fire! 🔥',
    victoryDesc: 'You\'ve crushed 80%+ of your day. What was your secret sauce today?',
    victorySaved: 'Day of Victory Logged! 🌟',
    chip_sleep: 'Good Sleep',
    chip_no_social: 'No Social Media',
    chip_early: 'Early Start',
    chip_mind: 'Focused Mind',
    chip_energy: 'High Energy',
    chip_coffee: 'Perfect Caffeine',
    chip_grit: 'Pure Grit',
    mode_standard: 'Standard',
    mode_crunch: 'Crunch',
    mode_light: 'Light',
    mode_review: 'Review',
    mode_battle_standard: 'Keep the balanced momentum going.',
    mode_battle_crunch: 'Push harder. Every second counts. 🔥',
    mode_battle_light: 'Focus on quality and recovery. 🌿',
    mode_battle_review: 'Analyze, adjust, and prepare. 🔍',
    survivalFocus: 'Survival Focus',
    essentialFocus: 'Essential Focus Only',
    newWeekTitle: 'New Week, New Focus.',
    setRhythm: 'Set your rhythm for the next 7 days.',
    beginJourney: 'Begin Journey',
    habitRitual: 'Build your ritual.',
    newRitual: 'New Ritual',
    createHabit: 'Create Habit',
    streak: 'Day Streak',
    voidDetected: 'Void detected',
    sortByRecent: 'Recent',
    sortByStreak: 'Streak',
    sortByName: 'Name',
    inboxTitle: 'Brain Dump',
    inboxSubtitle: 'Capture everything, worry later.',
    dumpThought: 'Dump a thought...',
    listening: 'Listening...',
    mindClear: 'Your mind is clear.',
    processIdea: 'Process Idea',
    aiRefine: 'AI Refine & Sync',
    localConvert: 'Fast Local Convert',
    discard: 'Discard Thought',
    leaveLater: 'Leave for later',
    language: 'Language',
    darkMode: 'Dark Mode',
    resetData: 'Reset All Data',
    resetConfirm: 'Are you sure?',
    resetDesc: 'This will wipe all your progress permanently.',
    level: 'Level',
    tasksDone: 'Tasks Done',
    challengesWon: 'Challenges',
    masteryProfile: 'Mastery Profile',
    victoryArchive: 'Victory Archive',
    trophyRoom: 'Trophy Room',
    totalMastery: 'Total Mastery',
    units: 'Units',
    peakPerformance: 'Peak Performance',
    focusArchetype: 'Focus Archetype',
    coreDomain: 'Core Domain',
    milestoneUnlocked: 'Milestone Unlocked',
    keepPushing: 'Keep pushing forward.',
    continuityMastery: 'Continuity is the mother of mastery.',
    evolutionDNA: 'Your productivity DNA is evolving.',
    novicePlanner: 'Novice Planner',
    productivityNinja: 'Productivity Ninja',
    masterFocus: 'Master of Focus',
    smartSuggestions: 'Smart Suggestions',
    appliedPreset: 'Applied {label} preset! ✨',
    deepReasoning: 'Deep Reasoning',
    aiSearching: 'Searching the web...',
    getLiveTip: 'Get Live Study Tip',
    searchResult: 'Found via Search',
    visualize: 'Visualize your progress',
    aiPlan: 'AI Planner',
    topPriorityShort: 'Top Priority',
    energyMeter: 'Energy Meter',
    psychologicalLoad: 'Psychological Load',
    overloadedWarning: 'Daily Capacity Exceeded! ⚠️',
    remainingEnergy: '{percent}% Energy Left',
    loadDescription: 'High priority tasks consume 1.5x more energy.',
    sources: 'Sources',
    noSources: 'No external sources used.',
    visitSource: 'Visit Source',
    reason_time: 'Not enough time',
    reason_energy: 'Low Energy',
    reason_procrastination: 'Procrastination',
    reason_unclear: 'Task Unclear',
    reason_not_important: 'Not Important',
    whyTrackerTitle: 'لماذا لم تنجز هذه المهمة؟',
    whyTrackerDesc: 'تتبع العقبات يساعد الذكاء الاصطناعي في تحسين يومك.',
    weeklyActivity: 'النشاط الأسبوعي',
    taskReminder: 'تذكير بمهمة',
    timeFor: 'حان وقت'
  },
  ar: {
    home: 'الرئيسية',
    tasks: 'المهام',
    habits: 'العادات',
    inbox: 'الوارد',
    stats: 'الإحصائيات',
    tips: 'نصائح',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    brainDump: 'تفريغ العقل',
    welcome: 'مرحباً',
    welcome_back: 'مرحباً بعودتك',
    goodMorning: 'صباح الخير',
    justBreathe: 'فقط تنفس.',
    topPriority: 'ما هو تركيزك اليوم؟',
    dailyFocus: 'التركيز اليومي',
    whatIsFocus: 'ما هو تركيزك لليوم؟',
    organizedDay: 'لنقم بتنظيم يومك.',
    welcomeUser: 'مرحباً، {name}',
    newTask: 'مهمة جديدة',
    editTask: 'تعديل المهمة',
    taskTitle: 'عنوان المهمة',
    label: 'العنوان',
    minutes: 'الدقائق',
    priority: 'الأولوية',
    category: 'الفئة',
    add: 'إضافة مهمة',
    update: 'تحديث المهمة',
    cancel: 'إلغاء',
    save: 'حفظ التغييرات',
    startTask: 'بدء المهمة',
    done: 'تم',
    todo: 'للقيام به',
    timeline: 'الجدول الزمني لليوم',
    urgent: 'عاجل',
    important: 'مهم',
    normal: 'عادي',
    startTimer: 'بدء المؤقت',
    running: 'قيد التنفيذ...',
    recordingFocus: 'تسجيل التركيز',
    remove: 'حذف',
    archiveDone: 'أرشفة المكتمل',
    listClear: 'القائمة فارغة',
    focusOutput: 'ركز على النتيجة، وليس الساعات.',
    organizeBtn: 'نظّم يومي',
    organizing: 'يفكر الذكاء الاصطناعي...',
    victoryTitle: 'لقد كنت متميزاً! 🔥',
    victoryDesc: 'لقد أنجزت أكثر من 80% من يومك. ما هو سر نجاحك اليوم؟',
    victorySaved: 'تم تسجيل يوم النصر! 🌟',
    chip_sleep: 'نوم جيد',
    chip_no_social: 'لا وسائل تواصل',
    chip_early: 'بداية مبكرة',
    chip_mind: 'عقل مركز',
    chip_energy: 'طاقة عالية',
    chip_coffee: 'كافيين مثالي',
    chip_grit: 'إرادة صلبة',
    mode_standard: 'قياسي',
    mode_crunch: 'مكثف',
    mode_light: 'خفيف',
    mode_review: 'مراجعة',
    mode_battle_standard: 'حافظ على التوازن المستمر.',
    mode_battle_crunch: 'اضغط بقوة أكبر. كل ثانية تهم. 🔥',
    mode_battle_light: 'ركز على الجودة والاستشفاء. 🌿',
    mode_battle_review: 'حلل، عدل، واستعد. 🔍',
    survivalFocus: 'تركيز النجاة',
    essentialFocus: 'التركيز الأساسي فقط',
    newWeekTitle: 'أسبوع جديد، تركيز جديد.',
    setRhythm: 'حدد إيقاعك للأيام السبعة القادمة.',
    beginJourney: 'ابدأ الرحلة',
    habitRitual: 'ابنِ طقوسك الخاصة.',
    newRitual: 'طقس جديد',
    createHabit: 'إنشاء عادة',
    streak: 'سلسلة أيام',
    voidDetected: 'لم يتم العثور على شيء',
    sortByRecent: 'الأحدث',
    sortByStreak: 'السلسلة',
    sortByName: 'الاسم',
    inboxTitle: 'تفريغ العقل',
    inboxSubtitle: 'سجل كل شيء، واقلق لاحقاً.',
    dumpThought: 'أفرغ فكرة...',
    listening: 'جاري الاستماع...',
    mindClear: 'عقلك صافٍ.',
    processIdea: 'معالجة الفكرة',
    aiRefine: 'تحسين ذكي ومزامنة',
    localConvert: 'تحويل محلي سريع',
    discard: 'تجاهل الفكرة',
    leaveLater: 'اتركها للاحق',
    language: 'اللغة',
    darkMode: 'الوضع الليلي',
    resetData: 'مسح جميع البيانات',
    resetConfirm: 'هل أنت متأكد؟',
    resetDesc: 'سيؤدي هذا إلى مسح كل تقدمك بشكل دائم.',
    level: 'المستوى',
    tasksDone: 'المهام المنجزة',
    challengesWon: 'التحديات',
    masteryProfile: 'ملف الإتقان',
    victoryArchive: 'أرشيف الانتصارات',
    trophyRoom: 'غرفة الأوسمة',
    totalMastery: 'الإتقان الكلي',
    units: 'وحدات',
    peakPerformance: 'ذروة الأداء',
    focusArchetype: 'نمط التركيز',
    coreDomain: 'المجال الأساسي',
    milestoneUnlocked: 'تم فتح إنجاز جديد',
    keepPushing: 'استمر في التقدم للأمام.',
    continuityMastery: 'الاستمرارية هي أم الإتقان.',
    evolutionDNA: 'حمضك النووي للإنتاجية يتطور.',
    novicePlanner: 'مخطط مبتدئ',
    productivityNinja: 'نينجا الإنتاجية',
    masterFocus: 'سيد التركيز',
    smartSuggestions: 'اقتراحات ذكية',
    appliedPreset: 'تم تطبيق الإعداد {label}! ✨',
    deepReasoning: 'تفكير عميق',
    aiSearching: 'جاري البحث في الويب...',
    getLiveTip: 'احصل على نصيحة دراسية مباشرة',
    searchResult: 'وُجد عبر البحث',
    visualize: 'تصور تقدمك',
    aiPlan: 'مخطط الذكاء الاصطناعي',
    topPriorityShort: 'الأولوية القصوى',
    energyMeter: 'مؤشر الطاقة',
    psychologicalLoad: 'الحمل النفسي',
    overloadedWarning: 'تجاوزت قدرتك اليومية! ⚠️',
    remainingEnergy: 'تبقي {percent}% من طاقتك',
    loadDescription: 'المهام العالية الأولوية تستهلك طاقة أكبر بـ 1.5 مرة.',
    sources: 'المصادر',
    noSources: 'لم يتم استخدام مصادر خارجية.',
    visitSource: 'زيارة المصدر',
    reason_time: 'ضيق الوقت',
    reason_energy: 'طاقة منخفضة',
    reason_procrastination: 'تسويف',
    reason_unclear: 'المهمة غير واضحة',
    reason_not_important: 'ليست مهمة',
    whyTrackerTitle: 'لماذا لم تنجز هذه المهمة؟',
    whyTrackerDesc: 'تتبع العقبات يساعد الذكاء الاصطناعي في تحسين يومك.',
    weeklyActivity: 'النشاط الأسبوعي',
    taskReminder: 'تذكير بمهمة',
    timeFor: 'حان وقت'
  }
};

export const Icons = {
  Home: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
  ),
  Tasks: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>
  ),
  AI: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>
  ),
  Stats: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>
  ),
  Tips: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>
  ),
  Settings: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1-2-2v-.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
  ),
  Check: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
  ),
  Plus: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
  ),
  Flame: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" stroke="none"><path d="M12 2C12 2 7 6.5 7 11s3 8 5 8 5-3.5 5-8-5-8.5-5-8.5zM12 16c-1.1 0-2-.9-2-2.1 0-1.1.9-2.1 2-2.1s2 .9 2 2.1c0 1.2-.9 2.1-2 2.1z"/></svg>
  ),
  Share: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/></svg>
  ),
  Mosque: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21h18"/><path d="M5 21v-7"/><path d="M19 21v-7"/><path d="M9 21v-4a3 3 0 0 1 6 0v4"/><path d="M2 11a10 10 0 0 1 20 0"/><path d="M12 2v2"/><path d="M12 7V5"/></svg>
  ),
  People: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
  ),
  Trophy: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/></svg>
  ),
  Coffee: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 8h1a4 4 0 1 1 0 8h-1"/><path d="M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4Z"/><line x1="6" y1="2" x2="6" y2="4"/><line x1="10" y1="2" x2="10" y2="4"/><line x1="14" y1="2" x2="14" y2="4"/></svg>
  ),
  Inbox: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></svg>
  ),
  Gear: () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1-2-2v-.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
  )
};